### ISSUE TITLE
Undefined symbols & segmentation fault

### ISSUE THREAD

**Issue by mwht** [unclechu/lv2-ladspa-bit-crusher#3]
When I open the plugin with Audacity, it reported following error:
```
lilv_lib_open(): error: Failed to open library /usr/lib/lv2/bit-crusher.lv2/bit-crusher.so (/usr/lib/lv2/bit-crusher.lv2/bit-crusher.so: undefined symbol: prepare_downsampling_knob)
```

LMMS however raises segmentation fault when audio is processed by plugin:
```
Notice: could not set realtime priority.
VST sync support disabled in your configuration
[1]    2766 segmentation fault (core dumped)  lmms
```

I've made a pull request with proposal to fix these errors. ( #2 )

**Comment by unclechu** [comment]
A fix released in [v0.3](https://github.com/unclechu/lv2-ladspa-bit-crusher/releases/tag/v0.3)
